#@#

name: test github runner
on:
  push:
    paths:
      - "**action-d**"

jobs:
  setup_env:
    runs-on: [self-hosted, linux, x64]
    env:
      KUBECONFIG: "kubeconfig/kubeconfig.conf"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - uses: azure/setup-kubectl@v3
        with:
           version: 'latest' # default is latest stable
        id: install_kubectl
      
      - name: test kubectl
        run: kubectl get node
      
      - uses: azure/k8s-create-secret@v2
        with:
          namespace: 'testtest'
          secret-name: docker-registry
          secret-type: regcred
          string-data: ${{ secrets.DOCKER_CONFIG }}      
      
      - name: setup helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install_helm
      
      - name: run helm
        run: |
          # helm upgrade test ./helm --install --dry-run
          helm upgrade test ./helm --install -n testtest --create-namespace