#

name: test azure & helm
on:
  push:
    paths:
      - "**action-b**"

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: 'ohm-gha'
          cluster-name: 'ohm-gha'
          # admin: 'false'
          # use-kubelogin: 'true'  
      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest' # default is latest stable
        id: install

      - name: test with kubectl
        run: |
          kubectl get node

      - name: setup helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install_helm
      
