#

name: test azure & helm
on:
  push:

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

<<<<<<< HEAD
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install
      
=======
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
      
>>>>>>> 6119f98811d7b8fefcce8b08b742b444b50a744c
