name: test event

on: 
  pull_request:
    types: [labeled]

jobs:

  setup-up-azure-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          echo $(github.event.pull_request.labels.*.name)

